[project]
repository-type = "library"
versioning-scheme = "library"
branching-model = "library-release"
release-model = "artifact-publishing"
primary-language = "rust"

[ci]
versions = ["1.92", "1.93"]
integration-tests = true

[markdownlint]
ignore = ["docs/site/docs"]

[publish]
release = true
docs = true

[dependencies]
vergil = "v2.0"
